import 'package:fasta/shipping/domain/entity/delivery.dart';
@Deprecated('use DeliverySummaryDTO')
class TripDTO extends Trip {
  TripDTO(
      {required String from,
      required String to,
      required String tripId,
      required String kilometer,
      required String distance,
      required String price,
      required String driverName,
      required String phoneNumber,
      required String email,
      required String vechicleNumber,
      required String createAt,
      required String status,
      required String senderName,
      required String pickupTime,
      required bool deliveryPriority,
      required String recieversName,
      required String receiversNumber,
      required String itemName,
      required String qty,
      required String value,
      required String weight,
      required String state,
      required String descriptionDetails,
      required String image,
      required String category,
      required String nameFrom,
      required String nameTo,
      required String vechicleType,
      required String rating,
      required String paymentMethod,
      required int id})
      : super(
            from: from,
            to: to,
            tripId: tripId,
            kilometer: kilometer,
            distance: distance,
            price: price,
            driverName: driverName,
            phoneNumber: phoneNumber,
            email: email,
            vechicleNumber: vechicleNumber,
            createAt: createAt,
            status: status,
            rider: driverName,
            departureTime: '',
            itemName: itemName,
            rating: rating,
            paymentMethod: paymentMethod,
            arrivalTime: '',
            id: id);
  factory TripDTO.fromJson(Map<String, dynamic> json) {
    return TripDTO(
        from: json['delivery']['fromAddress'],
        to: json['delivery']['toAddress'],
        tripId: json['deliveryId'].toString(),
        kilometer: json['delivery']['distance'].toString()+ ' Km',
        distance: json['delivery']['distance'].toString()+ ' Km',
        price: json['delivery']['cost'].toString()+' NGN',
        driverName: json['delivery']['driverId'].toString(),
        phoneNumber: '',
        email: "",
        vechicleNumber: json['delivery']['vehicleId'].toString(),
        createAt: json['createdAt'].toString(),
        status: json['status']??'',
        id: json['id'],
        category: json['delivery']['category']??'',
        deliveryPriority: json['delivery']['priority'],
        descriptionDetails: json['description_details']??'',
        image: json['delivery']['imageUrl'],
        itemName: json['item_name']??'',
        pickupTime: json['pickup_time']??"",
        nameTo: json['name_to']??"",
        qty: json['qty']??'',
        receiversNumber: json['receivers_number']??'',
        rating: json['rating']??"",
        recieversName: json['receivers_name']??"",
        state: json['state']??'',
        nameFrom: json['name_from']??'',
        vechicleType: json['delivery']['vehicleType'],
        value: json['value']??'',
        weight: json['weight']??'',
        senderName: json['sender_name']??'',
        paymentMethod: 'Wallet');
  }
}
