name: fasta
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  dartz: ^0.10.1
  freezed_annotation: ^1.0.0
  dio: ^4.0.0
  flutter_credit_card: ^3.0.1
  equatable: ^2.0.3
  bubble: ^1.2.1
  flutter_svg: ^1.0.3
  rounded_loading_button: ^2.0.8
  google_maps_flutter: ^2.1.4
  onesignal_flutter: ^3.3.2
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  pin_code_text_field: ^1.8.0
  timelines: ^0.1.0
  flutter_polyline_points: ^1.0.0
  flutter_contacts: ^1.1.4
  webview_flutter: ^3.0.4
  # image_picker: ^0.8.5+3
  images_picker: ^1.2.11
  cloudinary_public: ^0.11.0
  permission_handler: ^9.2.0
  flutter_google_places: ^0.3.0
  # socket_io_client: ^1.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  # sendbird_sdk: ^3.1.0
  
  # search_place_autocomplete: ^0.1.1
  maps_places_autocomplete: ^0.0.2
  flutter_otp_text_field: ^1.0.1
  intl: ^0.17.0
  google_sign_in: ^5.4.0
  infinite_scroll_pagination: 3.1.0
  
  # image_picker_widget: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  build_runner: ^2.1.5
  freezed: ^1.0.2
  import_sorter: ^4.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/4.0x/

# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/Logoblack.png
  android: true
  ios: true
  fullscreen: true


